packages:
- .
resolver: nightly-2020-06-22
extra-deps:
- aeson-1.5.0.0
- Cabal-3.2.0.0
- cryptonite-0.27
- directory-1.3.6.1
- http-client-0.7.0
- process-1.6.9.0
- time-1.10
- unix-2.7.2.2
allow-newer: true
