packages:
- .
resolver: nightly-2020-05-23
compiler: ghc-8.10.1
compiler-check: match-exact
extra-deps:
- aeson-1.5.0.0
- Cabal-3.2.0.0
- directory-1.3.6.1
- process-1.6.9.0
- time-1.10
- unix-2.7.2.2
allow-newer: true
