name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        resolver-yaml:
        - stack-14.27.yaml # GHC 8.6
        - stack-16.31.yaml # GHC 8.6
        - stack-18.28.yaml # GHC 8.10
        - stack.yaml # GHC 9.0
        - stack-nightly.yaml

    steps:
    - name: 'https://github.com/mstksg/setup-stack/issues/13'
      run: 'echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup stack
      uses: mstksg/setup-stack@v1

    - name: Install dependencies
      # hlint does not build on current stack nightly
      run: |
        if [ "$STACK_YAML" != "stack-nightly.yaml" ]; then stack --no-terminal --skip-ghc-check install hlint; fi
        stack --no-terminal --install-ghc test --only-dependencies
      env:
        STACK_YAML: ${{ matrix.resolver-yaml }}

    - name: Build
      run: |
        stack --no-terminal test --haddock --no-haddock-deps
        if [ "$STACK_YAML" != "stack-nightly.yaml" ]; then hlint .; fi
      env:
        STACK_YAML: ${{ matrix.resolver-yaml }}
