name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        resolver-yaml:
        - stack-14.27.yaml # GHC 8.6
        - stack-16.31.yaml # GHC 8.6
        - stack-18.28.yaml # GHC 8.10
        - stack-19.33.yaml # GHC 9.0
        - stack.yaml # GHC 9.2
        - stack-nightly.yaml

    steps:
    - name: 'https://github.com/mstksg/setup-stack/issues/13'
      run: 'echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup stack
      uses: haskell/actions/setup@v2
      with:
        enable-stack: true
        stack-version: latest

    - name: Set up HLint
      uses: haskell/actions/hlint-setup@v2

    - name: Install dependencies
      run: stack --no-terminal --install-ghc test --only-dependencies
      env:
        STACK_YAML: ${{ matrix.resolver-yaml }}

    - name: Test
      run: stack --no-terminal test --haddock --no-haddock-deps
      env:
        STACK_YAML: ${{ matrix.resolver-yaml }}

    - name: HLint
      uses: haskell/actions/hlint-run@v2
      with:
        path: .
        fail-on: warning
