name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        resolver-yaml:
        - stack-16.31.yaml # GHC 8.8
        - stack-18.28.yaml # GHC 8.10
        - stack-19.33.yaml # GHC 9.0
        - stack-20.26.yaml # GHC 9.2
        - stack-21.25.yaml # GHC 9.4
        - stack.yaml # GHC 9.6
        - stack-nightly.yaml

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup stack
      uses: haskell-actions/setup@v2
      with:
        enable-stack: true
        stack-version: latest

    - name: Set up HLint
      uses: haskell-actions/hlint-setup@v2

    - name: Install dependencies
      run: stack --no-terminal --install-ghc test --only-dependencies
      env:
        STACK_YAML: ${{ matrix.resolver-yaml }}

    - name: Test
      run: stack --no-terminal test --haddock --no-haddock-deps
      env:
        STACK_YAML: ${{ matrix.resolver-yaml }}

    - name: HLint
      uses: haskell-actions/hlint-run@v2
      with:
        path: .
        fail-on: warning
